
#pragma once

#define EGOERA_HASIERA		0
#define EGOERA_JOLASTEN		1
#define EGOERA_GALDUTA		2
#define EGOERA_IRABAZITA	3
#define EGOERA_RESET_BERDIN 4
#define EGOERA_RESET_BERRI	5

int EGOERA = EGOERA_HASIERA;
